# Generated by Django 3.0.8 on 2020-07-29 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='exact time when the data was collected')),
                ('image', models.ImageField(upload_to='employee_screenshots', verbose_name='screenshot itself')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee the activity was made by')),
            ],
            options={
                'db_table': 'employees_screenshots',
            },
        ),
        migrations.CreateModel(
            name='NetworkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='exact time when the data was collected')),
                ('host_name', models.CharField(max_length=2083)),
                ('message_count', models.IntegerField(default=0)),
                ('protocol_type', models.CharField(blank=True, choices=[('HTTP', 'Hypertext Transfer Protocol'), ('SSL/TLS', 'Secure Sockets Layer / Transport Layer Security')], default=None, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee the activity was made by')),
            ],
            options={
                'db_table': 'employees_network_messages',
            },
        ),
    ]
