# Generated by Django 3.0.8 on 2020-07-12 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee_screenshots', verbose_name='screenshot itself')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='exact time when the screenshot was taken')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee the screenshot is taken by')),
            ],
            options={
                'db_table': 'employees_screenshots',
                'ordering': ['date'],
            },
        ),
    ]
