# Generated by Django 3.0.8 on 2020-07-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200728_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='exact time when the data was collected'),
        ),
        migrations.CreateModel(
            name='NetworkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=2083)),
                ('message_count', models.IntegerField(default=0)),
                ('protocol_type', models.CharField(choices=[('Unknown', 'Unknown'), ('HTTP', 'Hypertext Transfer Protocol'), ('SSL', 'Secure Sockets Layer'), ('TLS', 'Transport Layer Security')], default='Unknown', max_length=255)),
                ('activity_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.ActivityInfo')),
            ],
            options={
                'db_table': 'employees_network_messages',
            },
        ),
    ]
