# Generated by Django 3.0.8 on 2020-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200728_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkactivity',
            name='message_type',
            field=models.CharField(blank=True, choices=[('Request', 'HTTP Request'), ('Response', 'HTTP Response'), ('Client hello', 'Client hello message'), ('Client hello', 'Server hello message')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='networkactivity',
            name='protocol_type',
            field=models.CharField(blank=True, choices=[('HTTP', 'Hypertext Transfer Protocol'), ('SSL', 'Secure Sockets Layer'), ('TLS', 'Transport Layer Security')], default=None, max_length=255, null=True),
        ),
    ]
