# Generated by Django 3.0.8 on 2020-08-19 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20200805_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvitationToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Invitation identifier.')),
                ('accepted', models.BooleanField(default=False, verbose_name='Whether or not the invitation was accepted by a new member')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='User that invited a new member.')),
                ('new_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_member', to=settings.AUTH_USER_MODEL, verbose_name='User that was invited.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'db_table': 'projects_projectinvitationtokens',
            },
        ),
    ]
